#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Default values
HOST=""
USER=""
PASSWORD=""
PORT="5432"  # Default PostgreSQL port
DB=""

# Function to display usage
usage() {
    echo "Usage: $0 [-u username] [-h hostname] [-p port] [-P password] -d database [pg_restore options]"
    exit 1
}

# Parse command-line arguments
while getopts "u:h:p:P:d:" opt; do
    case $opt in
        u) USER="$OPTARG" ;;
        h) HOST="$OPTARG" ;;
        p) PORT="$OPTARG" ;;
        P) PASSWORD="$OPTARG" ;;
        d) DB="$OPTARG" ;;
        *) usage ;;
    esac
done

# Check if database is provided
if [ -z "$DB" ]; then
    usage
fi

# Run pg_restore using Docker
docker run -it --rm \
    --network=host \
    -e PGPASSWORD="$PASSWORD" \
    -v "$(pwd):/backup" \
    postgres:latest pg_restore -h "$HOST" -U "$USER" -p "$PORT" -d "$DB" "$@"
